name: ci
on:
  pull_request:
    branches: ["main"]
jobs:
  ci:
    runs-on: ubuntu-22.04
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: pnpm
        run: npm install -g pnpm@9
      - name: cypress
        uses: cypress-io/github-action@v6
        with:
          start: pnpm start
      - name: test
        run: pnpm run test
